services:
  frontend:
    image: nginx:1.16.0-alpine
    ports:
      - 8082:80
    volumes:
      - ./front:/usr/share/nginx/html/
  api:
    image: php:8-apache
    ports:
      - 8081:80
    volumes:
      - ./api:/var/www/html/